[variables]
NIXPACKS_PYTHON_VERSION = "3.13"

[phases.setup]
nixPkgs = ["python313", "gcc"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && python manage.py migrate --noinput && gunicorn team_manager.wsgi:application --bind 0.0.0.0:$PORT"
